### ISSUE TITLE
need some gETH 

### ISSUE THREAD

**Issue by BetDEXben** [timbeiko/eth-roadmap-faq#7]
Hello @timbeiko . I'm a at-home staker and I want to run a prater node during the goerli merge as a prep for my mainnet node. Since people are requesting 320 goerli eth here and it's hard to come by lately, I will too. My address is 
0xbDa8eB0a84d893C22E37310A4f21B562d15B1900

**Comment by timbeiko** [comment]
@BetDEXben https://goerli.etherscan.io/tx/0x16d4b5c95e98566749eb9632957e63b4e251e2b5dc902ef0d2b87be5cd049bb7
